version: '3.7'

services:
  movie_service:
    build: ./movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service/:/app/
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${MOVIE_DATABASE_URL}
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
      - MOVIE_DATABASE_URL=${MOVIE_DATABASE_URL}

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${MOVIE_POSTGRES_DB}

  cast_service:
    build: ./cast_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast_service/:/app/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${CAST_DATABASE_URL}
      - CAST_DATABASE_URL=${CAST_DATABASE_URL}

  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${CAST_POSTGRES_DB}

  nginx:
      image: nginx:latest
      ports:
        - "8080:8080"
      volumes:
        - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - cast_service
        - movie_service

volumes:
  postgres_data_movie:
  postgres_data_cast: